document.writeln(" <header class=\'header-style header-style2 header-style3 header-style4\'>");
document.writeln("        <div class=\'hamburger-icon3\'>");
document.writeln("            <span></span>");
document.writeln("            <span></span>");
document.writeln("            <span></span>");
document.writeln("        </div>");
document.writeln("        <div class=\'header-content\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <div class=\'col-xs-6 col-sm-2\'>");
document.writeln("                    <a class=\'logo\' href=\'index.html\'>");
document.writeln("                        <img src=\'img/logo.png\' alt=\'#\' />");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-6 col-sm-10\'>");
document.writeln("                    <div class=\'hamburger-icon\'>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'hamburger-icon2\'>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                    </div>");
document.writeln("                    <nav class=\'normal-s\'>");
document.writeln("                        <ul>");
document.writeln("                            <li class=\'dropdown-plus\'>");
document.writeln("                                <a href=\'index.html\'>主页</a>");
document.writeln("                            </li>");
document.writeln("                           ");
document.writeln("                            <li class=\'active\'>");
document.writeln("                                <a href=\'blog.html\'>教程</a>");
document.writeln("                            </li>");
document.writeln("                             <li>");
document.writeln("                                <a href=\'resourcelist.html\'>资源</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown-plus\'>");
document.writeln("                                <a >关于</a>");
document.writeln("                                <span></span>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'about.html\'>关于</a></li>");
document.writeln("                                    <li><a href=\'connect.html\'>联系</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </li>");
document.writeln("                            ");
document.writeln("                        </ul>");
document.writeln("                    </nav>");
document.writeln("                </div>");
document.writeln("                <div class=\'section\'>");
document.writeln("                    <p>");
document.writeln("                    	<h6>Feri</h6>专注Java开发和教学多年，热衷分享Java学习教程，喜爱开源项目！");
document.writeln("                    </p>");
document.writeln("                </div>");
document.writeln("                <div class=\'category\'>");
document.writeln("                    <span class=\'small-1\'>分类</span>");
document.writeln("                    <ul>");
document.writeln("                        <li class=\'active\'>全部</li>");
document.writeln("                        <li>基本</li>");
document.writeln("                        <li>数据库</li>");
document.writeln("                        <li>Web</li>");
document.writeln("                        <li>框架</li>");
document.writeln("                        <li>架构</li>");
document.writeln("                        <li>开发神器</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'sort-by\'>");
document.writeln("                    <span class=\'small-1\'>排序</span>");
document.writeln("                    <ul>");
document.writeln("                        <li class=\'active\'>时间</li>");
document.writeln("                        <li>热度</li>");
document.writeln("                        <li>随机</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'normal-3 section\'>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'tel:+138(095)6526538\'>+18515990152</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'mailto:it_feri@163.com\'>it_feri@163.com</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <div class=\'empty-space h10-xs fl\'></div>");
document.writeln("                    <div class=\'follow\'>");
document.writeln("                        <a class=\'social\' href=\'https://www.facebook.com/\' target=\'_blank\'>");
document.writeln("                            <i class=\'fa fa-facebook\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                        <a class=\'social\' href=\'https://www.instagram.com/\' target=\'_blank\'>");
document.writeln("                            <i class=\'fa fa-instagram\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                        <a class=\'social\' href=\'https://www.pinterest.com/\' target=\'_blank\'>");
document.writeln("                            <i class=\'fa fa-pinterest-p\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                        <a class=\'social\' href=\'https://www.twitter.com/\' target=\'_blank\'>");
document.writeln("                            <i class=\'fa fa-twitter\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'mob-icon\'></div> ");
document.writeln("        </div>                                                          ");
document.writeln("    </header>");