document.writeln("<footer class=\'footer-style footer-style2\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <div class=\'col-md-3 col-sm-4 col-xs-12 text-left\'>");
document.writeln("                        <a class=\'logo\' href=\'index.html\'>");
document.writeln("                            <img src=\'img/logo.png\' alt=\'#\' />");
document.writeln("                        </a>");
document.writeln("                        <div class=\'empty-space h15-xs h0-md\'></div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'col-md-5 col-sm-8 col-xs-12\'>");
document.writeln("                        <nav class=\'small-2\'>");
document.writeln("                            <ul>");
document.writeln("                                <li class=\'footer-nav active\'>");
document.writeln("                                    <a href=\'index.html\'>主页</a>");
document.writeln("                                </li>");
document.writeln("                                <li class=\'footer-nav\'>");
document.writeln("                                    <a href=\'blog.html\'>教程</a>");
document.writeln("                                </li>");
document.writeln("                                <li class=\'footer-nav\'>");
document.writeln("                                <a href=\'resourcelist.html\'>资源</a>");
document.writeln("                            </li>");
document.writeln("                                 <li class=\'footer-nav\'>");
document.writeln("                                    <a href=\'about.html\'>关于</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </nav>");
document.writeln("                        <div class=\'empty-space h20-xs h0-md\'></div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'col-md-4 col-sm-12 text-right\'>");
document.writeln("                        <form class=\'subscribe-form\'>");
document.writeln("                            <div class=\'input-wrapper\'>");
document.writeln("                                <div class=\'input-style\'>");
document.writeln("                                    <input id=\'input\' name=\'email\' type=\'text\'>");
document.writeln("                                    <label for=\'input\'>输入邮箱……</label>");
document.writeln("                                </div>");
document.writeln("                                <button class=\'btn-style1\' type=\'submit\'><span>订阅</span></button>");
document.writeln("                            </div>");
document.writeln("                        </form>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'empty-space h40-xs fl\'></div>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <div class=\'col-xs-12\'>");
document.writeln("                        <div class=\'follow\'>");
document.writeln("                            <a class=\'social\' href=\'#\' target=\'_blank\'>");
document.writeln("                                <i class=\'fa fa-facebook\' aria-hidden=\'true\'></i>");
document.writeln("                            </a>");
document.writeln("                            <a class=\'social\' href=\'#\' target=\'_blank\'>");
document.writeln("                                <i class=\'fa fa-instagram\' aria-hidden=\'true\'></i>");
document.writeln("                            </a>");
document.writeln("                            <a class=\'social\' href=\'#\' target=\'_blank\'>");
document.writeln("                                <i class=\'fa fa-pinterest-p\' aria-hidden=\'true\'></i>");
document.writeln("                            </a>");
document.writeln("                            <a class=\'social\' href=\'#\' target=\'_blank\'>");
document.writeln("                                <i class=\'fa fa-twitter\' aria-hidden=\'true\'></i>");
document.writeln("                            </a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'empty-space h35-xs fl\'></div>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <div class=\'col-xs-12\'>");
document.writeln("                        <div class=\'copyright normal-s\'>");
document.writeln("                            Copyright &copy; 2019.Company name All rights reserved.More Templates <a href=\'http://www.cssmoban.com/\' target=\'_blank\' title=\'飞锐之家\'>飞锐之家</a> - Collect from ");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </footer>");