document.writeln("    <header class=\'header-style header-style2\'>");
document.writeln("        <div class=\'hamburger-icon3\'>");
document.writeln("            <span></span>");
document.writeln("            <span></span>");
document.writeln("            <span></span>");
document.writeln("        </div>");
document.writeln("        <div class=\'header-content\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <div class=\'col-xs-6 col-sm-2\'>");
document.writeln("                    <a class=\'logo\' href=\'index.html\'>");
document.writeln("                        <img src=\'img/logo.png\' alt=\'#\' />");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-xs-6 col-sm-10\'>");
document.writeln("                    <div class=\'hamburger-icon\'>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'hamburger-icon2\'>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                        <span></span>");
document.writeln("                    </div>");
document.writeln("                    <nav class=\'normal-s\'>");
document.writeln("                        <ul>");
document.writeln("                            <li class=\'dropdown-plus active\'>");
document.writeln("                                <a href=\'index.html\'>主页</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown-plus\'>");
document.writeln("                                <a href=\'blog.html\'>教程</a>");
document.writeln("                            </li>");
document.writeln("                             <li>");
document.writeln("                                <a href=\'resourcelist.html\'>资源</a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'about.html\'>关于</a>");
document.writeln("                            </li>");
document.writeln("                            ");
document.writeln("                        </ul>");
document.writeln("                    </nav>");
document.writeln("                </div>");
document.writeln("                <div class=\'section\'>");
document.writeln("                    <p>");
document.writeln("                    A small design & technology freelancer based out of Atlanta, GA. Catch up on my latest projects and get in touch.");
document.writeln("                    </p>");
document.writeln("                </div>");
document.writeln("                <div class=\'category\'>");
document.writeln("                    <span class=\'small-1\'>CATEGORY</span>");
document.writeln("                    <ul>");
document.writeln("                        <li class=\'active\'>All</li>");
document.writeln("                        <li>Development</li>");
document.writeln("                        <li>Illustration</li>");
document.writeln("                        <li>Product</li>");
document.writeln("                        <li>Typography</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'sort-by\'>");
document.writeln("                    <span class=\'small-1\'>SORT BY</span>");
document.writeln("                    <ul>");
document.writeln("                        <li>Random</li>");
document.writeln("                        <li class=\'active\'>Popular</li>");
document.writeln("                        <li>Rate</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'normal-3 section\'>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'tel:18515990152\'>18515990152</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'www.qfedu.com\'>千锋郑州Java欢迎你</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <div class=\'empty-space h10-xs fl\'></div>");
document.writeln("                    <div class=\'follow\'>");
document.writeln("                        <a class=\'social\' href=\'#\'>");
document.writeln("                            <i class=\'fa fa-facebook\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                        <a class=\'social\' href=\'#\'>");
document.writeln("                            <i class=\'fa fa-instagram\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                        <a class=\'social\' href=\'#\'>");
document.writeln("                            <i class=\'fa fa-pinterest-p\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                        <a class=\'social\' href=\'#\'>");
document.writeln("                            <i class=\'fa fa-twitter\' aria-hidden=\'true\'></i>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'mob-icon\'></div> ");
document.writeln("        </div>                                                          ");
document.writeln("    </header>");