document.writeln("<div class=\'overlay-wrapper height-min\'>");
document.writeln("        <div class=\'overlay-animation\'></div>");
document.writeln("        <div class=\'flex\'>");
document.writeln("            <div class=\'flex-in\'>");
document.writeln("                <div class=\'overlay-menu\'>");
document.writeln("                    <div class=\'container\'>");
document.writeln("                        <div class=\'row\'>");
document.writeln("                            <div class=\'btn-close\'><span></span><span></span></div>");
document.writeln("                            <div class=\'col-lg-2 col-lg-offset-5\'>");
document.writeln("                                <ul>");
document.writeln("                                    <li class=\'dropdown-plus\'>");
document.writeln("                                        <a href=\'index.html\'>主页</a>");
document.writeln("                                        <!--<span></span>-->");
document.writeln("                                        <!--<ul>");
document.writeln("                                            <li><a href=\'index.html\'>Home #1</a></li>");
document.writeln("                                            <li><a href=\'index2.html\'>Home #2</a></li>");
document.writeln("                                            <li><a href=\'index3.html\'>Home #3</a></li>");
document.writeln("                                            <li><a href=\'index4.html\'>Home #4</a></li>");
document.writeln("                                            <li><a href=\'index5.html\'>Home #5</a></li>");
document.writeln("                                        </ul>-->");
document.writeln("                                    </li>                       ");
document.writeln("                                    <li class=\'dropdown-plus\'>");
document.writeln("                                        <a href=\'blog.html\'>教程</a>");
document.writeln("                                       <!-- <span></span>");
document.writeln("                                        <ul>");
document.writeln("                                            <li><a href=\'blog.html\'>教程</a></li>");
document.writeln("                                        </ul>-->");
document.writeln("                                    </li>");
document.writeln("                                     <li>");
document.writeln("                                        <a href=\'resourcelist.html\' html\'>资源</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li>");
document.writeln("                                        <a href=\'contact.html\'>关于</a>");
document.writeln("                                    </li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");